const KEY='dovux-war-panel-v1';let state={territories:[],selected:null};
function load(){state=JSON.parse(localStorage.getItem(KEY)||'null')||{territories:DEFAULT_TERRITORIES,selected:null};}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render();}
function repLabel(v){return REP_LABELS[v]||'Sin datos'}
function sprayIcons(n){let out='';for(let i=0;i<3;i++)out+=i<n?'🧴':'▫️';return out}
function nextShift(){const now=new Date();const a=new Date(now),b=new Date(now);a.setHours(10,0,0,0);b.setHours(22,0,0,0);let next= now<a?a:now<b?b:new Date(now.getFullYear(),now.getMonth(),now.getDate()+1,10,0,0);let ms=next-now;let h=Math.floor(ms/36e5),m=Math.floor(ms%36e5/6e4);document.getElementById('nextShift').textContent=next.toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'});document.getElementById('shiftCountdown').textContent=`faltan ${h}h ${m}m`;}
function renderStats(){let t=state.territories;ownedCount.textContent=t.filter(x=>x.owner==='SixNine'||x.rep==101).length;targetCount.textContent=t.filter(x=>x.priority==='conquistar').length;sprayCount.textContent=t.reduce((a,b)=>a+(+b.sprays||0),0);riskCount.textContent=t.filter(x=>x.priority==='mantener'&&(+x.sprays||0)<3).length;}
function card(t){return `<article class="territory" style="border-left-color:${BANDS[t.owner]||'#00e5ff'}"><h3>${t.name||'Sin nombre'}</h3><div class="meta">${t.owner} · ${t.priority}</div><div class="sprays">${sprayIcons(+t.sprays||0)}</div><div class="rep"><span style="width:${Math.min(t.rep||0,100)}%"></span></div><div class="meta">Reputación: ${repLabel(t.rep)}</div><div class="actions"><button onclick="addSpray('${t.id}')">+ graffiti</button><button onclick="editTerritory('${t.id}')">Editar</button></div></article>`}
function renderTerritories(){territoryGrid.innerHTML=state.territories.map(card).join('');graffitiList.innerHTML=state.territories.filter(t=>(+t.sprays||0)>0).map(card).join('')||'<p class="meta">Todavía no hay graffitis cargados.</p>';}
function renderRecommendations(){let rec=[];state.territories.filter(t=>t.priority==='mantener'&&(+t.sprays||0)<3).sort((a,b)=>a.sprays-b.sprays).forEach(t=>{for(let i=t.sprays;i<3&&rec.length<4;i++)rec.push(t.name)});state.territories.filter(t=>t.priority==='conquistar'&&(+t.sprays||0)<3).sort((a,b)=>b.rep-a.rep||a.sprays-b.sprays).forEach(t=>{for(let i=t.sprays;i<3&&rec.length<4;i++)rec.push(t.name)});recommendations.innerHTML=rec.length?rec.map((r,i)=>`<div class="rec">${i+1}. Pintar en <b>${r}</b></div>`).join(''):'<div class="rec">Todo estable. Guardá graffitis para expansión.</div>';}
function render(){renderStats();renderTerritories();renderRecommendations();nextShift();}
function addSpray(id){let t=state.territories.find(x=>x.id===id);t.sprays=Math.min(3,(+t.sprays||0)+1);save();}
function editTerritory(id){state.selected=id;let t=state.territories.find(x=>x.id===id)||{id:crypto.randomUUID(),name:'',owner:'SixNine',priority:'conquistar',rep:10,sprays:0};dialogTitle.textContent=t.name||'Nuevo territorio';tName.value=t.name;tOwner.innerHTML=Object.keys(BANDS).map(b=>`<option ${t.owner===b?'selected':''}>${b}</option>`).join('');tPriority.value=t.priority;tRep.value=t.rep;tSprays.value=t.sprays;territoryDialog.showModal();}
function bind(){document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.view).classList.add('active')});document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');mapImg.src=`assets/mapas/${b.dataset.map}.png`});addTerritory.onclick=()=>{state.selected=null;editTerritory(null)};saveTerritory.onclick=e=>{e.preventDefault();let id=state.selected||crypto.randomUUID();let t=state.territories.find(x=>x.id===id);let data={id,name:tName.value||'Sin nombre',owner:tOwner.value,priority:tPriority.value,rep:+tRep.value,sprays:+tSprays.value||0};if(t)Object.assign(t,data);else state.territories.push(data);territoryDialog.close();save();};exportBtn.onclick=()=>navigator.clipboard.writeText(JSON.stringify(state,null,2)).then(()=>alert('Datos copiados'));resetDemo.onclick=()=>{localStorage.removeItem(KEY);load();render();};importBtn.onclick=()=>{try{state=JSON.parse(importBox.value);save()}catch(e){alert('JSON inválido')}};setInterval(nextShift,30000)}
load();bind();render();
