const STORAGE_KEY = 'factionos_v1_workspace';
const defaultState = {
  settings:{workspace:'SixNine',server:'DovuxGames',accent:'#d92332',turns:['10:00','22:00'],graffitiDurationHours:120,graffitisPerTurn:4,minGraffitis:3},
  organizations:[{id:id(),name:'SixNine',color:'#ff4d5e',relation:'propia'},{id:id(),name:'Heat Gang',color:'#8b5a2b',relation:'hostil'},{id:id(),name:'Young Yakuza',color:'#b89cff',relation:'neutral'}],
  territories:[
    terr('Davis Norte','SixNine','mantener','conquistado',26,62),terr('Terminal','SixNine','mantener','conquistado',54,78),terr('Merryweather','SixNine','mantener','conquistado',70,80),terr('Sandy Sur','SixNine','mantener','conquistado',66,28),terr('Forum Drive','Heat Gang','conquistar','alta',31,68)
  ],
  properties:[],events:[],activity:[]
};
function id(){return Math.random().toString(36).slice(2,10)}
function terr(name,owner,priority,rep,x,y){return {id:id(),name,owner,priority,reputation:rep,x,y,notes:'',graffitis:[]}}
let state = load();
let currentView='dashboard', selectedTerritory=null, moveMode=false;
const $ = s => document.querySelector(s);
const views = {dashboard:$('#dashboard'),operations:$('#operations'),logistics:$('#logistics'),events:$('#events'),builder:$('#builder'),settings:$('#settings')};
function load(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||defaultState}catch{return defaultState}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));render()}
function activeGraffitis(t){const now=Date.now();return (t.graffitis||[]).filter(g=>new Date(g.at).getTime()+state.settings.graffitiDurationHours*3600000>now)}
function nextExpiry(t){const active=activeGraffitis(t); if(!active.length)return null; return new Date(Math.min(...active.map(g=>new Date(g.at).getTime()+state.settings.graffitiDurationHours*3600000)))}
function status(t){const n=activeGraffitis(t).length;if(t.priority==='ignorar')return 'ignore'; if(n>=3)return 'safe'; if(n===2)return 'attention'; return 'risk'}
function repLabel(r){return ({muy_baja:'Muy baja',baja:'Baja',media:'Media',alta:'Alta',muy_alta:'Muy alta',conquistado:'Conquistado'}[r]||r||'Sin datos')}
function fmt(d){return d?new Intl.DateTimeFormat('es-AR',{dateStyle:'short',timeStyle:'short'}).format(d):'Sin vencimiento'}
function countdown(ms){if(ms<=0)return 'ahora'; const h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000); return `${h}h ${m}m`}
function nextTurn(){const now=new Date(); const turns=state.settings.turns||['10:00','22:00']; const candidates=turns.map(t=>{const [h,m]=t.split(':').map(Number);const d=new Date(now);d.setHours(h,m,0,0); if(d<=now)d.setDate(d.getDate()+1); return {label:t,date:d}}).sort((a,b)=>a.date-b.date); return candidates[0]}
function recommend(){let slots=state.settings.graffitisPerTurn; const rec=[]; const targets=[...state.territories].filter(t=>t.priority!=='ignorar').sort((a,b)=>{
 const order={mantener:0,conquistar:1,baja:2}; const sa=status(a),sb=status(b); const risk={risk:0,attention:1,safe:2,ignore:3}; return (risk[sa]-risk[sb])||(order[a.priority]-order[b.priority])||(activeGraffitis(a).length-activeGraffitis(b).length);
});
for(const t of targets){while(slots>0 && activeGraffitis(t).length + rec.filter(r=>r.id===t.id).length < state.settings.minGraffitis){rec.push({id:t.id,name:t.name});slots--}}
return rec.slice(0,state.settings.graffitisPerTurn);
}
function renderShell(){ $('#workspaceName').textContent=state.settings.workspace; document.documentElement.style.setProperty('--accent',state.settings.accent||'#d92332'); const nt=nextTurn(); $('#nextTurn').textContent=nt.label; $('#turnCountdown').textContent=countdown(nt.date-Date.now()); }
function setView(v){currentView=v;document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));Object.entries(views).forEach(([k,el])=>el.classList.toggle('active',k===v));$('#viewTitle').textContent={dashboard:'Dashboard',operations:'Operations',logistics:'Logistics',events:'Events',builder:'Builder',settings:'Settings'}[v];render()}
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));
function render(){renderShell(); renderDashboard(); renderOperations(); renderLogistics(); renderEvents(); renderBuilder(); renderSettings();}
function renderDashboard(){const terrs=state.territories.filter(t=>t.priority!=='ignorar');const risks=terrs.filter(t=>status(t)==='risk');const att=terrs.filter(t=>status(t)==='attention');const rec=recommend();views.dashboard.innerHTML=`<div class="grid cols-4"><div class="card"><p class="muted">Territorios</p><div class="stat">${terrs.length}</div><span class="pill">activos</span></div><div class="card"><p class="muted">Riesgo</p><div class="stat bad">${risks.length}</div><span class="pill">requieren atención</span></div><div class="card"><p class="muted">Atención</p><div class="stat warn">${att.length}</div><span class="pill">faltan graffitis</span></div><div class="card"><p class="muted">Graffitis</p><div class="stat">${state.territories.reduce((a,t)=>a+activeGraffitis(t).length,0)}</div><span class="pill">activos</span></div></div><div class="grid cols-2" style="margin-top:14px"><div class="card"><h3>Prioridad operativa</h3><div class="list">${[...risks,...att].slice(0,6).map(t=>`<div class="row"><span>${t.name}<br><small class="small">${t.priority} · ${activeGraffitis(t).length}/3 graffitis</small></span><b class="${status(t)==='risk'?'bad':'warn'}">${status(t)==='risk'?'Riesgo':'Atención'}</b></div>`).join('')||'<p class="muted">Sin alertas críticas.</p>'}</div></div><div class="card"><h3>Recomendación próximos 4</h3><div class="list">${rec.map((r,i)=>`<div class="row"><span>${i+1}. ${r.name}</span><b>🎨</b></div>`).join('')||'<p class="muted">No hay recomendaciones pendientes.</p>'}</div></div></div>`}
function renderOperations(){views.operations.innerHTML=`<div class="toolbar"><button class="primary" id="addTerritory">+ Territorio</button><button class="ghost" id="toggleMove">${moveMode?'Salir de mover':'Mover pines'}</button><button class="ghost" id="quickGraffiti">Registrar turno</button></div><div class="map-layout"><div class="map" id="map"></div><aside class="card" id="territoryPanel"></aside></div>`; $('#addTerritory').onclick=()=>territoryModal(); $('#toggleMove').onclick=()=>{moveMode=!moveMode;renderOperations()}; $('#quickGraffiti').onclick=quickTurnModal; const map=$('#map'); state.territories.forEach(t=>{const p=document.createElement('button');p.className=`pin ${selectedTerritory===t.id?'focus':''} ${status(t)==='risk'?'risk':''}`;p.style.left=t.x+'%';p.style.top=t.y+'%';p.style.borderColor=(state.organizations.find(o=>o.name===t.owner)||{}).color||'#fff';p.textContent=t.name;p.onclick=(e)=>{e.stopPropagation(); selectedTerritory=t.id; renderOperations()};map.appendChild(p)}); map.onclick=e=>{if(moveMode&&selectedTerritory){const rect=map.getBoundingClientRect();const t=state.territories.find(x=>x.id===selectedTerritory);t.x=((e.clientX-rect.left)/rect.width*100).toFixed(2);t.y=((e.clientY-rect.top)/rect.height*100).toFixed(2);save()}}; renderTerritoryPanel();}
function renderTerritoryPanel(){const panel=$('#territoryPanel'); const t=state.territories.find(x=>x.id===selectedTerritory)||state.territories[0]; if(!t){panel.innerHTML='<h3>Sin territorios</h3><p class="muted">Creá uno desde Builder u Operations.</p>';return} selectedTerritory=t.id; const n=activeGraffitis(t).length; const exp=nextExpiry(t); panel.innerHTML=`<span class="pill">${t.priority}</span><h3 style="font-size:26px">${t.name}</h3><p class="muted">Controla: <b>${t.owner||'Sin asignar'}</b></p><p>Reputación: <b>${repLabel(t.reputation)}</b></p><div class="sprays">${'🎨'.repeat(n)}${'⚪'.repeat(Math.max(0,3-n))}</div><p class="muted">Próximo vencimiento: ${fmt(exp)}</p><p class="muted">${exp?'Falta '+countdown(exp-Date.now()):'Sin graffitis activos'}</p><div class="grid"><button class="primary" id="addGraf">+ Agregar graffiti</button><button class="ghost" id="editTerr">Editar</button><button class="danger" id="clearGraf">Limpiar graffitis</button></div><h3>Graffitis</h3><div class="list">${activeGraffitis(t).map((g,i)=>`<div class="row"><span>#${i+1}<br><small class="small">${fmt(new Date(g.at))}</small></span><button class="ghost" data-delg="${g.id}">Eliminar</button></div>`).join('')||'<p class="muted">Sin graffitis activos.</p>'}</div>`; $('#addGraf').onclick=()=>{t.graffitis=t.graffitis||[];t.graffitis.push({id:id(),at:new Date().toISOString()});state.activity.unshift({at:new Date().toISOString(),text:`Graffiti agregado en ${t.name}`});save()}; $('#editTerr').onclick=()=>territoryModal(t); $('#clearGraf').onclick=()=>{t.graffitis=[];save()}; panel.querySelectorAll('[data-delg]').forEach(b=>b.onclick=()=>{t.graffitis=t.graffitis.filter(g=>g.id!==b.dataset.delg);save()})}
function renderLogistics(){views.logistics.innerHTML=`<div class="toolbar"><button class="primary" id="newProp">+ Nueva propiedad</button></div><div class="grid cols-3">${state.properties.map(p=>`<div class="card"><h3>${p.icon||'🏠'} ${p.name}</h3><p class="muted">${p.type||'Propiedad'}</p><div class="list">${(p.items||[]).slice(0,6).map(it=>`<div class="row"><span>${it.name}<br><small class="small">${it.category||'General'}</small></span><b>${it.qty} ${it.unit||''}</b></div>`).join('')||'<p class="muted">Sin objetos.</p>'}</div><button class="ghost" data-prop="${p.id}">Administrar</button></div>`).join('')||'<div class="card"><h3>Sin propiedades</h3><p class="muted">Creá casas, depósitos o galpones desde acá.</p></div>'}</div>`; $('#newProp').onclick=()=>propertyModal(); views.logistics.querySelectorAll('[data-prop]').forEach(b=>b.onclick=()=>propertyModal(state.properties.find(p=>p.id===b.dataset.prop)))}
function renderEvents(){views.events.innerHTML=`<div class="toolbar"><button class="primary" id="newEvent">+ Nuevo evento</button></div><div class="card"><h3>Agenda</h3><div class="list">${state.events.map(ev=>`<div class="row"><span>${ev.name}<br><small class="small">${ev.type||'Evento'} · ${ev.time||''}</small></span><button class="ghost" data-event="${ev.id}">Editar</button></div>`).join('')||'<p class="muted">Sin eventos cargados.</p>'}</div></div>`; $('#newEvent').onclick=()=>eventModal(); views.events.querySelectorAll('[data-event]').forEach(b=>b.onclick=()=>eventModal(state.events.find(e=>e.id===b.dataset.event)))}
function renderBuilder(){views.builder.innerHTML=`<div class="tabs"><button class="tab active">Constructor</button></div><div class="grid cols-3"><div class="card"><h3>Organizaciones</h3><p class="muted">Bandas/facciones externas.</p><button class="primary" id="newOrg">+ Organización</button><div class="list">${state.organizations.map(o=>`<div class="row"><span style="color:${o.color}">${o.name}</span><button class="ghost" data-org="${o.id}">Editar</button></div>`).join('')}</div></div><div class="card"><h3>Territorios</h3><p class="muted">Mapa, reputación y prioridades.</p><button class="primary" onclick="document.querySelector('[data-view=operations]').click()">Abrir Operations</button></div><div class="card"><h3>Logística</h3><p class="muted">Casas, categorías y objetos.</p><button class="primary" onclick="document.querySelector('[data-view=logistics]').click()">Abrir Logistics</button></div></div>`; $('#newOrg').onclick=()=>orgModal(); views.builder.querySelectorAll('[data-org]').forEach(b=>b.onclick=()=>orgModal(state.organizations.find(o=>o.id===b.dataset.org)))}
function renderSettings(){views.settings.innerHTML=`<div class="card"><h3>Workspace</h3><div class="form-grid"><label>Nombre<input id="setWorkspace" value="${state.settings.workspace}"></label><label>Servidor<input id="setServer" value="${state.settings.server}"></label><label>Color principal<input id="setAccent" type="color" value="${state.settings.accent}"></label><label>Turnos<input id="setTurns" value="${state.settings.turns.join(',')}"></label><label>Duración graffiti (horas)<input id="setDur" type="number" value="${state.settings.graffitiDurationHours}"></label><label>Graffitis por turno<input id="setPer" type="number" value="${state.settings.graffitisPerTurn}"></label></div><button class="primary" id="saveSettings">Guardar configuración</button></div>`; $('#saveSettings').onclick=()=>{state.settings.workspace=$('#setWorkspace').value;state.settings.server=$('#setServer').value;state.settings.accent=$('#setAccent').value;state.settings.turns=$('#setTurns').value.split(',').map(x=>x.trim()).filter(Boolean);state.settings.graffitiDurationHours=Number($('#setDur').value);state.settings.graffitisPerTurn=Number($('#setPer').value);save()}}
function openModal(html){$('#modal').innerHTML=`<div class="modal-box">${html}</div>`;$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}
function territoryModal(t={}){openModal(`<h3>${t.id?'Editar':'Nuevo'} territorio</h3><div class="form-grid"><label>Nombre<input id="tName" value="${t.name||''}"></label><label>Controla<select id="tOwner">${state.organizations.map(o=>`<option ${t.owner===o.name?'selected':''}>${o.name}</option>`).join('')}</select></label><label>Prioridad<select id="tPriority">${['mantener','conquistar','ignorar','baja'].map(p=>`<option ${t.priority===p?'selected':''}>${p}</option>`).join('')}</select></label><label>Reputación<select id="tRep">${['muy_baja','baja','media','alta','muy_alta','conquistado'].map(r=>`<option ${t.reputation===r?'selected':''} value="${r}">${repLabel(r)}</option>`).join('')}</select></label></div><label>Notas<textarea id="tNotes">${t.notes||''}</textarea></label><div class="actions"><button class="ghost" id="cancel">Cancelar</button><button class="primary" id="saveT">Guardar</button></div>`);$('#cancel').onclick=closeModal;$('#saveT').onclick=()=>{if(t.id){Object.assign(t,{name:$('#tName').value,owner:$('#tOwner').value,priority:$('#tPriority').value,reputation:$('#tRep').value,notes:$('#tNotes').value})}else state.territories.push({id:id(),name:$('#tName').value,owner:$('#tOwner').value,priority:$('#tPriority').value,reputation:$('#tRep').value,notes:$('#tNotes').value,x:50,y:50,graffitis:[]});closeModal();save()}}
function orgModal(o={}){openModal(`<h3>${o.id?'Editar':'Nueva'} organización</h3><div class="form-grid"><label>Nombre<input id="oName" value="${o.name||''}"></label><label>Color<input id="oColor" type="color" value="${o.color||'#ffffff'}"></label><label>Relación<select id="oRel">${['propia','aliada','neutral','hostil','guerra'].map(r=>`<option ${o.relation===r?'selected':''}>${r}</option>`).join('')}</select></label></div><div class="actions"><button class="ghost" id="cancel">Cancelar</button><button class="primary" id="saveO">Guardar</button></div>`);$('#cancel').onclick=closeModal;$('#saveO').onclick=()=>{if(o.id)Object.assign(o,{name:$('#oName').value,color:$('#oColor').value,relation:$('#oRel').value});else state.organizations.push({id:id(),name:$('#oName').value,color:$('#oColor').value,relation:$('#oRel').value});closeModal();save()}}
function propertyModal(p={}){openModal(`<h3>${p.id?'Administrar':'Nueva'} propiedad</h3><div class="form-grid"><label>Nombre<input id="pName" value="${p.name||''}"></label><label>Tipo<input id="pType" value="${p.type||'Casa'}"></label><label>Icono<input id="pIcon" value="${p.icon||'🏠'}"></label></div>${p.id?`<h3>Objetos</h3><div class="list">${(p.items||[]).map(it=>`<div class="row"><span>${it.name}<br><small class="small">${it.category||'General'}</small></span><b>${it.qty}</b></div>`).join('')||'<p class="muted">Sin objetos.</p>'}</div><div class="form-grid"><label>Objeto<input id="iName"></label><label>Categoría<input id="iCat"></label><label>Cantidad<input id="iQty" type="number" value="0"></label><label>Unidad<input id="iUnit" value="u"></label></div><button class="ghost" id="addItem">+ Agregar objeto</button>`:''}<div class="actions"><button class="ghost" id="cancel">Cerrar</button><button class="primary" id="saveP">Guardar</button></div>`);$('#cancel').onclick=closeModal;if(p.id&&$('#addItem'))$('#addItem').onclick=()=>{p.items=p.items||[];p.items.push({id:id(),name:$('#iName').value,category:$('#iCat').value,qty:Number($('#iQty').value),unit:$('#iUnit').value});closeModal();save()};$('#saveP').onclick=()=>{if(p.id)Object.assign(p,{name:$('#pName').value,type:$('#pType').value,icon:$('#pIcon').value});else state.properties.push({id:id(),name:$('#pName').value,type:$('#pType').value,icon:$('#pIcon').value,items:[]});closeModal();save()}}
function eventModal(ev={}){openModal(`<h3>${ev.id?'Editar':'Nuevo'} evento</h3><div class="form-grid"><label>Nombre<input id="eName" value="${ev.name||''}"></label><label>Tipo<input id="eType" value="${ev.type||''}"></label><label>Horario<input id="eTime" value="${ev.time||''}"></label><label>Repetición<input id="eRep" value="${ev.repeat||''}"></label></div><div class="actions"><button class="ghost" id="cancel">Cancelar</button><button class="primary" id="saveE">Guardar</button></div>`);$('#cancel').onclick=closeModal;$('#saveE').onclick=()=>{if(ev.id)Object.assign(ev,{name:$('#eName').value,type:$('#eType').value,time:$('#eTime').value,repeat:$('#eRep').value});else state.events.push({id:id(),name:$('#eName').value,type:$('#eType').value,time:$('#eTime').value,repeat:$('#eRep').value});closeModal();save()}}
function quickTurnModal(){const rec=recommend();openModal(`<h3>Registrar turno</h3><p class="muted">Recomendación automática según riesgos y prioridades.</p><div class="list">${rec.map(r=>`<div class="row"><span>${r.name}</span><b>🎨</b></div>`).join('')||'Sin recomendaciones.'}</div><div class="actions"><button class="ghost" id="cancel">Cancelar</button><button class="primary" id="applyRec">Aplicar recomendación</button></div>`);$('#cancel').onclick=closeModal;$('#applyRec').onclick=()=>{rec.forEach(r=>{const t=state.territories.find(x=>x.id===r.id);t.graffitis.push({id:id(),at:new Date().toISOString()})});closeModal();save()}}
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`factionos-${state.settings.workspace}.json`;a.click()};
$('#importInput').onchange=e=>{const f=e.target.files[0]; if(!f)return; const r=new FileReader();r.onload=()=>{state=JSON.parse(r.result);save()};r.readAsText(f)};
setInterval(renderShell,1000);render();
