const $=id=>document.getElementById(id);
function initGangOptions(){gangInput.innerHTML=Object.keys(CONFIG.gangs).map(g=>`<option>${g}</option>`).join('')}
function repLabel(v){return CONFIG.reputation[Number(v)]||'Sin rep.'}
function selectTerritory(id){selected=state.territories.find(t=>t.id===id); if(!selected)return; editorEmpty.classList.add('hidden'); editor.classList.remove('hidden'); selectedTitle.textContent=selected.name||'Sin nombre'; selectedId.textContent=selected.id; nameInput.value=selected.name||''; gangInput.value=selected.gang||'Neutral'; priorityInput.value=selected.priority||'ignorar'; repInput.value=String(selected.rep||0); notesInput.value=selected.notes||''; renderSpraySlots(selected); renderMap();}
function renderSpraySlots(t){const sprays=activeSprays(t); spraySlots.innerHTML=''; for(let i=0;i<3;i++){const s=sprays[i]; const div=document.createElement('div'); div.className='spray '+(s?sprayStatus(s):'empty'); div.innerHTML=s?`🧴<small>${timeLeft(sprayExpires(s)-now())}</small>`:'🧴'; spraySlots.appendChild(div);}}
function saveSelected(){if(!selected)return; selected.name=nameInput.value.trim(); selected.gang=gangInput.value; selected.priority=priorityInput.value; selected.rep=Number(repInput.value); selected.notes=notesInput.value.trim(); saveState(); renderAll(); selectTerritory(selected.id)}
function renderSummary(){const arr=state.territories; const active=arr.reduce((a,t)=>a+activeSprays(t).length,0); activeSpraysEl.textContent=active; const crit=arr.filter(t=>t.priority!=='ignorar'&&activeSprays(t).length<3).length; criticalCount.textContent=crit; summary.innerHTML=`<div class='summary-line'><span>Total territorios</span><b>${arr.length}</b></div><div class='summary-line'><span>Mantener</span><b>${arr.filter(t=>t.priority==='mantener').length}</b></div><div class='summary-line'><span>Conquistar</span><b>${arr.filter(t=>t.priority==='conquistar').length}</b></div><div class='summary-line'><span>Ignorar</span><b>${arr.filter(t=>t.priority==='ignorar').length}</b></div><div class='summary-line'><span>Graffitis activos</span><b>${active}</b></div>`}
function renderCommander(){const rec=recommendations(); recommendationsEl.innerHTML=rec.length?'':'<p class="muted">No hay acciones urgentes. Revisá mantener/conquistar.</p>'; rec.forEach(r=>{const d=document.createElement('div'); d.className='recommendation'; d.innerHTML=`<div><b>${r.territory.name||r.territory.id}</b><div class='reason'>${r.reason}</div></div><span class='tag'>${r.qty} 🧴</span>`; recommendationsEl.appendChild(d);});}
function renderClock(){const nt=nextTurn(); nextTurn.textContent=nt.toLocaleString('es-AR',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'2-digit'});}
function renderAll(){cleanExpired(); renderMap(); renderSummary(); renderCommander(); renderClock();}
btnMapLS.onclick=()=>setMap('ls'); btnMapNorth.onclick=()=>setMap('north'); btnDraw.onclick=beginDraw; btnFinish.onclick=finishDraw; btnCancel.onclick=cancelDraw; saveTerritory.onclick=saveSelected; deleteTerritory.onclick=()=>{if(selected&&confirm('¿Eliminar territorio?')){state.territories=state.territories.filter(t=>t.id!==selected.id);selected=null;saveState();editor.classList.add('hidden');editorEmpty.classList.remove('hidden');renderAll();}}; addSpray.onclick=()=>selected&&addSprayTo(selected); clearSprays.onclick=()=>selected&&clearTerritorySprays(selected); exportData.onclick=()=>{dataBox.value=exportState();dataBox.select()}; importData.onclick=()=>{try{importState(dataBox.value)}catch(e){alert('JSON inválido')}};
const activeSpraysEl=$('activeSprays'), recommendationsEl=$('recommendations');
initGangOptions(); setMap(state.currentMap||'ls'); setInterval(renderAll,60000);
