let state=loadState(), selected=null, drawing=false, draft=[];
const svg=document.getElementById('mapSvg');
function setMap(map){state.currentMap=map; saveState(); selected=null; const cfg=CONFIG.maps[map]; svg.setAttribute('viewBox',cfg.viewBox.join(' ')); document.getElementById('btnMapLS').classList.toggle('active',map==='ls'); document.getElementById('btnMapNorth').classList.toggle('active',map==='north'); renderAll();}
function centroid(points){let x=0,y=0; points.forEach(p=>{x+=p[0];y+=p[1]}); return [x/points.length,y/points.length]}
function svgPoint(evt){const r=svg.getBoundingClientRect(); const [x,y,w,h]=CONFIG.maps[state.currentMap].viewBox; return [Math.round(x+(evt.clientX-r.left)/r.width*w),Math.round(y+(evt.clientY-r.top)/r.height*h)];}
function renderMap(){
  const cfg=CONFIG.maps[state.currentMap]; svg.innerHTML='';
  const img=document.createElementNS('http://www.w3.org/2000/svg','image'); img.setAttribute('href',cfg.image); img.setAttribute('x',cfg.viewBox[0]); img.setAttribute('y',cfg.viewBox[1]); img.setAttribute('width',cfg.viewBox[2]); img.setAttribute('height',cfg.viewBox[3]); svg.appendChild(img);
  state.territories.filter(t=>t.map===state.currentMap).forEach(t=>{
    const p=document.createElementNS('http://www.w3.org/2000/svg','polygon'); p.setAttribute('points',t.points.map(pt=>pt.join(',')).join(' ')); p.setAttribute('fill',CONFIG.gangs[t.gang]||'#64748b'); p.setAttribute('fill-opacity',t.priority==='ignorar'?'.22':'.48'); p.setAttribute('stroke',t.priority==='mantener'?'#ffffff':t.priority==='conquistar'?'#facc15':'#94a3b8'); p.setAttribute('stroke-width',selected&&selected.id===t.id?'4':'2'); p.classList.add('territory'); if(selected&&selected.id===t.id)p.classList.add('selected'); p.onclick=(e)=>{e.stopPropagation();selectTerritory(t.id)}; svg.appendChild(p);
    if(t.points.length){const [cx,cy]=centroid(t.points); const txt=document.createElementNS('http://www.w3.org/2000/svg','text'); txt.setAttribute('x',cx); txt.setAttribute('y',cy-8); txt.setAttribute('text-anchor','middle'); txt.classList.add('territory-label'); txt.textContent=t.name||t.id; svg.appendChild(txt); const rep=document.createElementNS('http://www.w3.org/2000/svg','text'); rep.setAttribute('x',cx); rep.setAttribute('y',cy+8); rep.setAttribute('text-anchor','middle'); rep.classList.add('territory-rep'); rep.textContent=CONFIG.reputation[t.rep]||'Sin rep.'; svg.appendChild(rep); const cans=document.createElementNS('http://www.w3.org/2000/svg','text'); cans.setAttribute('x',cx); cans.setAttribute('y',cy+24); cans.setAttribute('text-anchor','middle'); cans.classList.add('spray-mini'); cans.textContent='🧴'.repeat(activeSprays(t).length); svg.appendChild(cans);}
  });
  if(draft.length){const poly=document.createElementNS('http://www.w3.org/2000/svg','polyline'); poly.setAttribute('points',draft.map(pt=>pt.join(',')).join(' ')); poly.classList.add('draw-line'); svg.appendChild(poly); draft.forEach(pt=>{const c=document.createElementNS('http://www.w3.org/2000/svg','circle'); c.setAttribute('cx',pt[0]); c.setAttribute('cy',pt[1]); c.setAttribute('r',4); c.classList.add('vertex'); svg.appendChild(c);});}
}
svg.addEventListener('click',e=>{if(drawing){draft.push(svgPoint(e)); renderMap();}});
function beginDraw(){drawing=true;draft=[];btnDraw.classList.add('hidden');btnFinish.classList.remove('hidden');btnCancel.classList.remove('hidden')}
function cancelDraw(){drawing=false;draft=[];btnDraw.classList.remove('hidden');btnFinish.classList.add('hidden');btnCancel.classList.add('hidden');renderMap()}
function finishDraw(){if(draft.length<3){alert('Necesitás al menos 3 puntos.');return} const id='T-'+String(state.territories.length+1).padStart(3,'0'); const t={id,map:state.currentMap,points:draft,name:'',gang:'Neutral',priority:'ignorar',rep:0,notes:'',sprays:[]}; state.territories.push(t); drawing=false;draft=[];btnDraw.classList.remove('hidden');btnFinish.classList.add('hidden');btnCancel.classList.add('hidden');saveState();renderAll();selectTerritory(id)}
